name: CI

on:
  push:
    branches: [ main ]

  # Allows you to run the workflow manually from the Actions tab
  workflow_dispatch:
    # Inputs the workflow accepts
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made of one or more jobs that can run sequentially or in parallel
jobs: 
  # This workflow contains a single workflow called "build"
  greet: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest # windows-latest, macos

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs a single command using the runners shell
      - name: Send greeting
        run: echo "Hello ${{github.event.inputs.name}}"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test and deploy your project.
